apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app.kubernetes.io/name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: diesel-migrations
          image: localhost:5001/kube-obs-init:0.1
      containers:
        - name: api
          image: localhost:5001/kube-obs-api:0.1
          env:
            - name: DATABASE_URL
              value: "postgres://admin:admin@postgresql-dev.default.svc.cluster.local/obs"
          ports:
            - containerPort: 80
---

