apiVersion: v1
kind: Namespace
metadata:
  name: observer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-controller
  namespace: observer
  labels:
    app.kubernetes.io/name: obs-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: obs-controller
      containers:
        - name: controller
          image: localhost:5001/kube-obs-controller:0.1
          env:
            - name: API_SERVER_URL
              value: "http://api-service.default.svc.cluster.local:9090"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: obs-controller
  namespace: observer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obs-controller-clusterrole
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - "*"
    resources:
      - "upscalers"
    verbs:
      - get
      - watch
      - list
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: obs-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: obs-controller-clusterrole
subjects:
  - kind: ServiceAccount
    name: obs-controller
    # change the namespace name below if you want to deploy to a different namespace
    namespace: observer
