# OOM metrics undetected #2848
# https://github.com/kubernetes-sigs/kind/issues/2848
# not working atm
apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-2
spec:
  containers:
    - name: memory-demo-2-ctr
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-3
spec:
  containers:
    - name: memory-demo-2-ctr
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
